config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls, name='adminka'),
    path('', include('main.urls')),  # подключаем файл urls.py из приложения main

    path('accounts/', include('allauth.urls')),
    path('gallery/', include('gallery.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.http import HttpResponse
from .views import AdvertListView,AdvertDetailView,AdvertCreate,\
    AdvertUpdate,AdvertDelete


def testView(request):
    ''' Тестовый метод для проверки запуска тестовой страницы '''
    return HttpResponse('<div align="center"><h1 style= "color:blue">Это тестовая страница!</h1></div>')


urlpatterns = [
    #    path('',testView), #Эндпоинт для запуска тестового метода
    path('', AdvertListView.as_view(), name='adv_list'),
    path('create/', AdvertCreate.as_view(), name='adv_create'),
    path('detail/<int:pk>', AdvertDetailView.as_view(), name='adv_detail'),
    path('update/<int:pk>', AdvertUpdate.as_view(), name='adv_update'),
    path('delete/<int:pk>', AdvertDelete.as_view(), name='adv_delete'),

    #path('photos/', PhotolistView.as_view(), name='photos_list'),
    #path('photocreate/', UsersAddPhotoView.as_view(), name='photo_create'),



]

main/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.admin import User


def get_path_image(uname, iname):
    '''формирую имя файла картинки.
    к имени спереди добавляю путь - папку, с именем пользователя, где будет
    храниться картинка.
    Если этого не делать все будут в одной папке'''
    path = str(uname).lower() + '/' + str(iname)
    return path


class Gallery(models.Model):
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    title = models.CharField(verbose_name='Описание', max_length=50, blank=True, null=True)

    class Meta:
        ordering = ['title']

    def get_detailUrl(self):
        return reverse('gallery_update', kwargs={'pk': self.pk})

    def get_deleteUrl(self):
        return reverse('gallery_delete', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Advert(models.Model):
    '''
    Модель Advert, для хранения информации Рекламного объявления
    '''
    title = models.CharField(verbose_name='заглавие', max_length=50)
    text = models.TextField(verbose_name='Текст объявления', null=True, blank=True)
    phone = models.CharField(verbose_name='Телефон', max_length=20, null=True, blank=True)
    email = models.EmailField(verbose_name='Email', max_length=40, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    gallery = models.ForeignKey(Gallery, verbose_name='Галерея', on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'
        ordering = ['-date']

    def __str__(self):
        return self.title

    def get_detailUrl(self):
        return reverse('adv_detail', kwargs={'pk': self.pk})

    def get_absolute_url(self):
        return reverse("adv_list")

    def get_UpdateUrl(self):
        return reverse('adv_update', kwargs={'pk': self.pk})

    def get_DeleteUrl(self):
        return reverse('adv_delete', kwargs={'pk': self.pk})

    def get_photo_gallery_list(self):
        return reverse('photo_gallery_list', kwargs={'pk': self.pk})


class Photo(models.Model):
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    title = models.CharField(verbose_name='Описание', max_length=50, blank=True, null=True)
    image = models.ImageField(verbose_name='Фотография', upload_to='gallery/')
    # advert = models.ForeignKey(Advert, verbose_name='Объявление', on_delete=models.CASCADE)
    gallery = models.ForeignKey(Gallery, verbose_name='Галерея', on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        ''' переопределяю метод save
        чтоб изменить значения image.name
        '''
        self.image.name = get_path_image(self.user, self.image.name)
        super().save(*args, **kwargs)

    # def get_photogallerylistUrl(self):
    #     return reverse('photo_list', kwargs={'gallery': self.gallery})

    def get_PhotodeleteUrl(self):
        return reverse('photo_delete', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Фотограция'
        verbose_name_plural = 'Фотографии'
        ordering = ['user', 'gallery', 'title']

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Title</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Advert</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'adv_list' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Меню пользователя
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'adv_create' %}">Новое объявление</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'gallery_list' %}">Мои Галереи</a>
                    <a class="dropdown-item" href="{% url 'gallery_create' %}">Новая Галерея</a>
                    <a class="dropdown-item" href="{% url 'photo_create' %}">Добавить фото</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            {% endif%}
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>

        {% if user.is_authenticated %}
        <a href="{% url 'adv_create' %}" type="button" class="btn btn-warning"> Создать объявление </a>
        {% endif %}
        &nbsp;&nbsp;&nbsp;&nbsp;
        <form class="form-inline my-2 my-lg-0" action="{% url 'adv_list' %}" method="get">
            <input class="form-control mr-sm-2" name="val" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>

        {% if user.is_authenticated %}
        <span><b> &nbsp; {{ user.username }}&nbsp; </b></span>
        <a class="nav-link" href="{% url 'account_logout' %}">Выйти</a>
        {% else %}
        <a class="nav-link" href="{% url 'account_login' %}">Вход</a>
        <a class="nav-link" href="{% url 'account_signup' %}">Регистрация</a>
        {% endif %}


    </div>
</nav>


{% block content %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>
</html>

templates/paginator.html
{% block paginator %}
{% if is_paginated %}
<div class="pagination">
    <nav aria-label="...">
        <ul class="pagination">
            {% if page_obj.has_previous %} <!--Если есть предыдущая страница-->
            <li class="page-item">
                {% if search %}
                <a class="page-link" href="{{ request.path }}?val={{search}}&page={{ page_obj.previous_page_number }}" tabindex="-1"
                   aria-disabled="true">Previous</a>
                {% else %}
                <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}" tabindex="-1"
                   aria-disabled="true">Previous</a>
                {% endif %}
            </li>
            {% else %} <!--Нет предыдущей страницы-->
            <li class="page-item disabled">
                <a class="page-link" href="">Previous</a>
            </li>
            {% endif %}

            {% for n in paginator.page_range %} <!--Цикл по количеству страниц-->

            {% if page_obj.number == n %} <!--Если это текущая страница-->
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">{{ n }}<span class="sr-only">(current)</span></a>
            </li>
            {% else %} <!--Это не текущая страница-->

            {% if search %}
            <li class="page-item"><a class="page-link" href="{{ request.path }}?val={{search}}&page={{ n }}">{{ n }}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="{{ request.path }}?page={{ n }}">{{ n }}</a></li>
            {% endif %}

            {% endif %}
            {% endfor%}

            {% if page_obj.has_next %} <!--Если есть Следующая страница-->
            <li class="page-item">
                {% if search %}
                <a class="page-link" href="{{ request.path }}?val={{search}}&page={{ page_obj.next_page_number }}">Next</a>
                {% else %}
                <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
                {% endif %}
            </li>
            {% else %} <!--Нет следующей страницы-->
            <li class="page-item disabled">
                <a class="page-link" href="">Next</a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endif %}

{% endblock %}